import { Button, VerticalBox, LineEdit, CheckBox, HorizontalBox, ComboBox } from "std-widgets.slint";

enum SupportedImageFormats {
    Png,
    WebP,
    Bmp,
    Jpeg
}

export component AppWindow inherits Window {
    // Window Properties
    title: "Formatify";
    icon: @image-url("assets/images/FormatifyAppIcon.png");
    max-height: 500px;
    min-height: 480px;
    max-width: 540px;
    min-width: 509px;
    full-screen: false;
    background: #1e1f22;

    // Callbacks
    callback ButtonSelectImageClicked();
    callback ButtonSelectImageOutputClicked();
    callback ButtonApplyChangesClicked([string], string, string, SupportedImageFormats);
    callback SelectFileFormat(int);

    // Wating Screen Callbacks
    callback ShowWatingScreen(bool);
    callback UpdateWatingText(string);
    callback ExitWatingScreen();

    // Main Properties
    in-out property <[string]> image-path;
    in-out property <string> image-output-path;
    out property <string> output-image-name;
    in-out property <SupportedImageFormats> format-selected: SupportedImageFormats.Png;
    out property <[string]> supported-image-formats: ["Png", "WebP", "Bmp", "Jpeg"];

    // Wating Screen Properties
    out property <string> message;
    out property <bool> show-wating-screen: false;
    in-out property <bool> can-exit-wating-screen: false;

    VerticalLayout {
        padding: 50px;
        alignment: center;
        spacing: 25px;

        Text {
            text: "Formatify";
            font-size: 40px;
            font-weight: 800;
            horizontal-alignment: center;
        }
        // Select Image Box
        HorizontalBox {
            alignment: center;
            spacing: 25px;
            Button {
                width: 100px;
                primary: true;
                text: "Select Images";
                clicked => {
                    root.ButtonSelectImageClicked();
                }
            }

            edit-image-path := LineEdit {
                width: 200px;
                font-size: 25px;
                read-only: true;
                text: image-path[0];
                horizontal-alignment: center;
            }
        }

        // Select Output Path
        HorizontalBox {
            alignment: center;
            spacing: 25px;
            Button {
                width: 150px;
                primary: true;
                text: "Select Output";
                clicked => {
                    root.ButtonSelectImageOutputClicked();
                }
            }

            edit-image-output-path := LineEdit {
                width: 200px;
                font-size: 18px;
                read-only: true;
                text: root.image-output-path;
                horizontal-alignment: center;
            }
        }

        HorizontalBox {
            alignment: center;
            spacing: 25px;

            Text {
                text: "File Name";
                font-size: 18px;
                horizontal-alignment: center;
            }

            LineEdit {
                width: 200px;
                font-size: 18px;
                horizontal-alignment: center;
                placeholder-text: "Enter File Name";
                accepted(text) => {
                    output-image-name = self.text;
                }
                edited(text) => {
                    output-image-name = self.text;
                }
            }
        }

        HorizontalBox {
            alignment: center;
            spacing: 25px;
            ComboBox {
                model: supported-image-formats;
                current-index: 0;
                width: 100px;
                selected(current-value) => {
                    root.SelectFileFormat(self.current-index);
                }
            }
        }

        HorizontalBox {
            alignment: center;
            spacing: 25px;
            // Confirem Changes
            Button {
                width: 150px;
                primary: true;
                text: "Convert";
                enabled: CanConvert();
                clicked => {
                    root.ButtonApplyChangesClicked(image-path,image-output-path,output-image-name,format-selected);
                }
            }
        }
    }  

    Rectangle {
        width: parent.width;
        height: parent.height;
        visible: root.show-wating-screen;
        Rectangle {
            width: parent.width;
            height: parent.height;
            background: black;
            opacity: 0.95;
        }

        Text {
            font-size: 20px;
            height: 100px;
            width: 500px;
            text: message;
            horizontal-alignment: TextHorizontalAlignment.center;
            vertical-alignment: TextVerticalAlignment.center;
            wrap: TextWrap.word-wrap;
        }

        TouchArea {
            width: parent.width;
            height: parent.height;
            enabled: root.show-wating-screen;
        }

        TouchArea {
            width: parent.width;
            height: parent.height;
            enabled: can-exit-wating-screen;
            clicked => {
                ShowWatingScreen(false);
                ExitWatingScreen();
            }
        }
    }

    ShowWatingScreen(show) => {
        show-wating-screen = show;
    }

    UpdateWatingText(text) => {
        message = text;
    }

    function CanConvert() -> bool {
        return image-path.length > 0 && image-output-path != "" && output-image-name != "";
    }
}
